### ISSUE TITLE
多么有用的 action helper

### ISSUE THREAD

**Issue by EthanLin-TWer** [ariesjia/redux-actions-helper#1]
虽然和嘉爷见面不多，合作也不多，不过嘉爷这套 action helper 在我现在见过的 TW 深圳项目里好像已经成了标配啊😂很多地方都在用。偶然发现已经开源，看来以后可以直接 `npm install` 了，哈哈。

啊。我是林从羽。

**Comment by fengyunhe** [comment]
能否将文档稍微完善下，有些看不懂它的作用。readme最后那句话说的pending,success,failed 是什么情况用

**Comment by ariesjia** [comment]
> 能否将文档稍微完善下，有些看不懂它的作用。readme最后那句话说的pending,success,failed 是什么情况用

这是5年之前的，现在不建议使用他。 
会自动生成异步的3个状态（pending,success,failed ）的action, 可以简化一些订阅模板。
